### ISSUE TITLE
Document the Chuck Norris APIs on Wiki Page

### ISSUE THREAD

**Issue by chenry** [grjug/ChuckNorrisJokes#1]
Please create high level documentation for all operations available for the Chuck Norris API.  Please provide the following for each operation:
- URL
- Example JSON Responses

**Comment by foxefj** [comment]
I am almost done with this and should be able to update soon.

**Comment by chenry** [comment]
Any thoughts on how to integrate it with this git repo.....?

**Comment by chenry** [comment]
This has been completed. Thanks Eric.

Please refer to the wiki.
