### ISSUE TITLE
Create Main Activity as Entry Point for various parts of application

### ISSUE THREAD

**Issue by chenry** [grjug/ChuckNorrisJokes#13]
Create a new Main Activity that will be the entry point for the various parts of the application.  The various parts, currently are:
- Random Joke - one joke on the screen (random)
- Category List
  - contains list of known categories
  - clicking on the category will take you to a ListView of jokes
  - clicking on a list view item will allow you to see the joke in full screen
  - will be able to page through the jokes by swiping left and right on the activity
- Settings Page
  - will allow you to choose whether you want explicit jokes included or not
- Add Joke
  - will allow you to add a joke to the local database

**Comment by foxefj** [comment]
dibs - this is mine

**Comment by chenry** [comment]
This has been completed.  Thanks Eric.
