### ISSUE TITLE
Create Data Model to support Chuck Norris API

### ISSUE THREAD

**Issue by chenry** [grjug/ChuckNorrisJokes#2]
In order to support the Chuck Norris API, we are going to need a data model created.  Basically this includes objects that can be populated with the fields that are returned from all of the json calls.

**Comment by etrian-odysseus** [comment]
Calling it! Maybe later I will figure out how to actually own it.

**Comment by chenry** [comment]
Unfortunately you cannot own it.  There doesn't seem to be a way to assign this to you...oh well, it is yours.

Thanks

**Comment by chenry** [comment]
I am updating this to have getters and setters, as well as an equals code for the specific joke.  I also changed the case of the java class to ProperCase.
