### ISSUE TITLE
Design a Database Model in order to support offline storage of jokes

### ISSUE THREAD

**Issue by chenry** [grjug/ChuckNorrisJokes#3]
In order to be able to use the application offline, we need the ability to store the jokes in a local database.  This task is to work on the database model for storing these jokes.

**Comment by etrian-odysseus** [comment]
I'll work on this one.

**Comment by etrian-odysseus** [comment]
Design completed, sent Carlus the invite to view it

**Comment by chenry** [comment]
Looks good. I think the only thing I can think of that is missing is the thumbs up.  Also, when it comes to implementation the I'd columns should be _id. 

Thanks

**Comment by etrian-odysseus** [comment]
Cool, I'll add it. Are you going to do a separate issue for the implementation?

**Comment by chenry** [comment]
Yes.  I will also close this issue.

Thanks

**Comment by chenry** [comment]
This should have been closed....thanks
