### ISSUE TITLE
Build Chuck Norris API Integration Layer

### ISSUE THREAD

**Issue by chenry** [grjug/ChuckNorrisJokes#5]
This task includes all of the coding necessary in order to build the integration layer of the Android application to the Chuck Norris API.

There are two ways that this can be done, brute force, or with a library.  I personally would be curious in hearing more about a library from Google specifically for Android called Volley.  You can learn more about that project here:

https://www.captechconsulting.com/blog/clinton-teegarden/android-volley-library-tutorial

**Comment by foxefj** [comment]
I am already looking into this - so I am claiming it :).

**Comment by chenry** [comment]
This has been completed.
