### ISSUE TITLE
Create DAO and Basic CRUD operations

### ISSUE THREAD

**Issue by chenry** [grjug/ChuckNorrisJokes#6]
Create DAO and Basic CRUD operations.

For inspiration, refer to the following:
http://www.androidhive.info/2011/11/android-sqlite-database-tutorial/

**Comment by etrian-odysseus** [comment]
I'll take this one.

**Comment by chenry** [comment]
Another site that you will gain a lot of information from, specifically for creating foreign keys and things of that nature.....is this:

https://www.sqlite.org/

FKs - https://www.sqlite.org/foreignkeys.html

**Comment by chenry** [comment]
Awesome work Joe....thanks!!!!
